language: r
os: linux
cache: packages
warnings_are_errors: true
r_check_args: --as-cran # --no-manual # Workaround error compiling PDF manual
jobs:
  include:
    - r: 3.4.0 # vdiffr fails before 3.4.
    - r: release
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      r_binary_packages:
       - covr
       - devtools
       - knitr
       - rmarkdown
       - roxygen2
       - testthat
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        cleanup: false
        skip_cleanup: true
        local_dir: "docs"
        keep-history: true
        on: 
          branch: master
    - r: devel
      r_binary_packages:
         - covr
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      r: release
      before_install:
      #- brew install cairo # Already installed
      - sudo tlmgr install doi titling hyperref
#  allow_failures:
#    r: osx # Problem with devtools?

git:
  depth: 1

r_packages:
  - devtools
  - testthat
  - vdiffr

before_script:
  - R -e "devtools::document()"

notifications:
  email:
    on_success: change
    on_failure: change
